
Import('env')

test_env = env.Clone()

tests = [
    "getuid",
    "helloworld",
    "hellodebug",
    "network_basic",
    "kqueue",
    "rand",
    "read",
    "setuid",
    "thread_basic",
    "thread_mutex",
    "thread_print",
    "time",
    "fork_basic",
    "rdtsc",
    "loadstore_volatile",
    "atomics",
]

test_env.Append(CPPFLAGS = ["--sysroot=$SYSROOT",
                            "-Xclang", "-load", "-Xclang", "$CASTORPASS"])
test_env.Append(LINKFLAGS = ["-static", "--sysroot=$SYSROOT"])
test_env.Append(LIBS = ["thr", "c"])

for t in tests:
    test_env.Depends(t+".c", "CastorPass")
    test_env.Program(t, [ "../lib/Runtime/libCastorRuntime.o", t+".c"])

