
import os

Import('env')

test_env = env.Clone()

tests = [ ]
for f in Glob('#test/*.c'):
    tests.append(os.path.basename(f.rstr()[0:-2]))

testbench_deps = [ "CastorRuntime",
		   "CastorPass",
                   Glob("#test/*.c") ]

test_env.Append(CPPFLAGS = ["--sysroot=$SYSROOT",
                            "-Xclang", "-load", "-Xclang", "$CASTORPASS"])
test_env.Append(LINKFLAGS = ["--sysroot=$SYSROOT"])
test_env.Append(LIBS = ["thr", "c"])

for t in tests:
    test_env.Depends(t+".o", ["CastorRuntime", "CastorPass"])
    t = test_env.Program(t, [t+".c"])
    testbench_deps.append(t)

AlwaysBuild(Alias('testbench', testbench_deps, "test/testbench.py"))

