#!/bin/sh
(grep '__strong' ../../lib/Runtime/events.c | cut -d',' -f2 | cut -d')' -f1 | sed 's/^[ _]*//'; grep INTERPOS_ ../../lib/Runtime/events.c | cut -d'[' -f2 | cut -d']' -f1 | sed 's/INTERPOS_//') | sort | uniq
