#!/bin/sh
(grep '__strong' ../../lib/Runtime/events* | cut -d',' -f2 | cut -d')' -f1 | sed 's/^[ _]*//'; grep INTERPOS_ ../../lib/Runtime/events* | cut -d'[' -f2 | cut -d']' -f1 | sed 's/INTERPOS_//'; grep 'BIND_REF' ../../lib/Runtime/events* | cut -d'(' -f2 | cut -d')' -f1) | sort | uniq
