
Import('env')

src = [
    "rrtool.cc"
]

env.Program("rrtool", src,
            LINKFLAGS = ["-static"],
            LIBPATH = ["#build/lib/Common"],
            LIBS = ["elf", "execinfo", "edit", "c++", "CastorCommon"])
