
Import('env')

src = [
    "events_thread.c",
    "threadid.c"
]

# Made global to make compilation_db work
env["CPPPATH"].append("/usr/src/lib/libc/include")

rt = env.StaticLibrary("CastorThreadRuntime", src)

env.Alias("CastorThreadRuntime", rt)

