
Import('env')

src = [
    "events_thread.c",
    "threadid.c"
]

# Made global to make compilation_db work
env["CPPPATH"].append("/usr/src/lib/libc/include")

env.StaticLibrary("CastorThreadRuntime", src)
rt = env.SharedLibrary("libcastor_thr.so", src,
                       LIBPATH = ["#build/lib/Runtime"], LIBS = ["libsys_castor.so"])

env.Alias("CastorThreadRuntime", rt)

