
Import('env')

src = [
    "events_thread.c",
    "threadid.c"
]

# Made global to make compilation_db work
env["CPPPATH"].append("/usr/src/lib/libc/include")

rt = env.SharedLibrary("libcastor_thr.so", src,
                       LIBPATH = ["#build/lib/Runtime"], LIBS = ["libsys_castor.so"])

#rt = env.CopyFile("$SYSROOT/usr/lib/libCastorThreadRuntime.a",
#                  "#build/lib/ThreadRuntime/libCastorThreadRuntime.a")
env.Alias("CastorThreadRuntime", rt)

