
Import('env')

env.Program("replay", ["replay.c"],
            LINKFLAGS = ["-static"],
            LIBPATH = ["#build/lib/Common"],
            LIBS = ["elf", "execinfo", "edit", "pthread", "ncurses", "CastorCommon"])

