
/*** !!! this code has been autogenerated by utils/gen_sal.py, do not modify it directly. !!! ***/


#include <stdio.h>
#include <errno.h>
#include <time.h>
#include <signal.h>


#include <unistd.h>
#include <fcntl.h>
#include <dirent.h>
#include <kenv.h>
#include <poll.h>

#include <semaphore.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/ptrace.h>
#include <sys/event.h>
#include <sys/socket.h>
#include <sys/uio.h>
#include <sys/resource.h>
#include <sys/param.h>
#include <sys/cpuset.h>
#include <sys/mount.h>
#include <sys/syscall.h>
#include <sys/stat.h>
#include <sys/capsicum.h>
#include <sys/extattr.h>
#include <sys/time.h>
#include <sys/uuid.h>
#include <sys/reboot.h>
#include <ufs/ufs/quota.h>
#include <sys/timex.h>
#include <sys/timeffc.h>
#include <sys/rctl.h>
#include <bsm/audit.h>
#include <sys/ucred.h>

#ifndef GEN_SAL

#include <castor/debug.h>
#include <castor/rrlog.h>
#include <castor/rrplay.h>
#include <castor/rrgq.h>
#include <castor/mtx.h>
#include <castor/events.h>

#endif
#include "castor_xlat.h"
#include "rrlog.h"
void
pretty_print_FORK(RRLogEntry entry)
{
    printf("fork");
    printf("(");
    printf(") = %d", (pid_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_READ(RRLogEntry entry)
{
    printf("read");
    if ((int)entry.value[0] != -1) {
	printf("(%d, buf, _", (int)entry.objectId);
    } else {
	printf("(%d, buf, _", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_WRITE(RRLogEntry entry)
{
    printf("write");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_OPEN(RRLogEntry entry)
{
    printf("open");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CLOSE(RRLogEntry entry)
{
    printf("close");
    printf("(%d", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LINK(RRLogEntry entry)
{
    printf("link");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_UNLINK(RRLogEntry entry)
{
    printf("unlink");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CHDIR(RRLogEntry entry)
{
    printf("chdir");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FCHDIR(RRLogEntry entry)
{
    printf("fchdir");
    printf("(%d", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CHMOD(RRLogEntry entry)
{
    printf("chmod");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CHOWN(RRLogEntry entry)
{
    printf("chown");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETPID(RRLogEntry entry)
{
    printf("getpid");
    printf("(");
    printf(") = %d", (pid_t) entry.value[0]);

    printf("\n");
}

void
pretty_print_MOUNT(RRLogEntry entry)
{
    printf("mount");
    printf("(_, _, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_UNMOUNT(RRLogEntry entry)
{
    printf("unmount");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETUID(RRLogEntry entry)
{
    printf("setuid");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETUID(RRLogEntry entry)
{
    printf("getuid");
    printf("(");
    printf(") = %d", (uid_t) entry.value[0]);

    printf("\n");
}

void
pretty_print_GETEUID(RRLogEntry entry)
{
    printf("geteuid");
    printf("(");
    printf(") = %d", (uid_t) entry.value[0]);

    printf("\n");
}

void
pretty_print_RECVMSG(RRLogEntry entry)
{
    printf("recvmsg");
    if ((int)entry.value[0] != -1) {
	printf("(%d, msg, _", (int)entry.objectId);
    } else {
	printf("(%d, msg, _", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SENDMSG(RRLogEntry entry)
{
    printf("sendmsg");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RECVFROM(RRLogEntry entry)
{
    printf("recvfrom");
    if ((int)entry.value[0] != -1) {
	printf("(%d, buf, _, _, from, fromlenaddr", (int)entry.objectId);
    } else {
	printf("(%d, buf, _, _, from, fromlenaddr", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_ACCEPT(RRLogEntry entry)
{
    printf("accept");
    if ((int)entry.value[0] != -1) {
	printf("(%d, name, anamelen", (int)entry.objectId);
    } else {
	printf("(%d, name, anamelen", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETPEERNAME(RRLogEntry entry)
{
    printf("getpeername");
    if ((int)entry.value[0] != -1) {
	printf("(%d, asa, alen", (int)entry.objectId);
    } else {
	printf("(%d, asa, alen", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETSOCKNAME(RRLogEntry entry)
{
    printf("getsockname");
    if ((int)entry.value[0] != -1) {
	printf("(%d, asa, alen", (int)entry.objectId);
    } else {
	printf("(%d, asa, alen", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_ACCESS(RRLogEntry entry)
{
    printf("access");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CHFLAGS(RRLogEntry entry)
{
    printf("chflags");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FCHFLAGS(RRLogEntry entry)
{
    printf("fchflags");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETPPID(RRLogEntry entry)
{
    printf("getppid");
    printf("(");
    printf(") = %d", (pid_t) entry.value[0]);

    printf("\n");
}

void
pretty_print_DUP(RRLogEntry entry)
{
    printf("dup");
    printf("(%d", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETEGID(RRLogEntry entry)
{
    printf("getegid");
    printf("(");
    printf(") = %d", (gid_t) entry.value[0]);

    printf("\n");
}

void
pretty_print_GETGID(RRLogEntry entry)
{
    printf("getgid");
    printf("(");
    printf(") = %d", (gid_t) entry.value[0]);

    printf("\n");
}

void
pretty_print_ACCT(RRLogEntry entry)
{
    printf("acct");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_IOCTL(RRLogEntry entry)
{
    printf("ioctl");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, data", (int)entry.objectId);
    } else {
	printf("(%d, _, data", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_REBOOT(RRLogEntry entry)
{
    printf("reboot");
    printf("(%d", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SYMLINK(RRLogEntry entry)
{
    printf("symlink");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_READLINK(RRLogEntry entry)
{
    printf("readlink");
    if ((int)entry.value[0] != -1) {
	printf("(_, buf, _");
    } else {
	printf("(_, buf, _");
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_UMASK(RRLogEntry entry)
{
    printf("umask");
    printf("(_");
    printf(") = %d", (mode_t) entry.value[0]);

    printf("\n");
}

void
pretty_print_CHROOT(RRLogEntry entry)
{
    printf("chroot");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETGROUPS(RRLogEntry entry)
{
    printf("getgroups");
    if ((int)entry.value[0] != -1) {
	printf("(%d, gidset", (int)entry.objectId);
    } else {
	printf("(%d, gidset", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETGROUPS(RRLogEntry entry)
{
    printf("setgroups");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETITIMER(RRLogEntry entry)
{
    printf("setitimer");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, oitv", (int)entry.objectId);
    } else {
	printf("(%d, _, oitv", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SWAPON(RRLogEntry entry)
{
    printf("swapon");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETITIMER(RRLogEntry entry)
{
    printf("getitimer");
    if ((int)entry.value[0] != -1) {
	printf("(%d, itv", (int)entry.objectId);
    } else {
	printf("(%d, itv", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETDTABLESIZE(RRLogEntry entry)
{
    printf("getdtablesize");
    printf("(");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_DUP2(RRLogEntry entry)
{
    printf("dup2");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FCNTL(RRLogEntry entry)
{
    printf("fcntl");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SELECT(RRLogEntry entry)
{
    printf("select");
    if ((int)entry.value[0] != -1) {
	printf("(%d, in, ou, ex, _", (int)entry.objectId);
    } else {
	printf("(%d, in, ou, ex, _", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FSYNC(RRLogEntry entry)
{
    printf("fsync");
    printf("(%d", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETPRIORITY(RRLogEntry entry)
{
    printf("setpriority");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SOCKET(RRLogEntry entry)
{
    printf("socket");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CONNECT(RRLogEntry entry)
{
    printf("connect");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETPRIORITY(RRLogEntry entry)
{
    printf("getpriority");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_BIND(RRLogEntry entry)
{
    printf("bind");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETSOCKOPT(RRLogEntry entry)
{
    printf("setsockopt");
    printf("(%d, _, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LISTEN(RRLogEntry entry)
{
    printf("listen");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETTIMEOFDAY(RRLogEntry entry)
{
    printf("gettimeofday");
    if ((int)entry.value[0] != -1) {
	printf("(tp, tzp");
    } else {
	printf("(tp, tzp");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETRUSAGE(RRLogEntry entry)
{
    printf("getrusage");
    if ((int)entry.value[0] != -1) {
	printf("(%d, rusage", (int)entry.objectId);
    } else {
	printf("(%d, rusage", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETSOCKOPT(RRLogEntry entry)
{
    printf("getsockopt");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, _, val, avalsize", (int)entry.objectId);
    } else {
	printf("(%d, _, _, val, avalsize", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_READV(RRLogEntry entry)
{
    printf("readv");
    if ((int)entry.value[0] != -1) {
	printf("(%d, iovp, _", (int)entry.objectId);
    } else {
	printf("(%d, iovp, _", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_WRITEV(RRLogEntry entry)
{
    printf("writev");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETTIMEOFDAY(RRLogEntry entry)
{
    printf("settimeofday");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FCHOWN(RRLogEntry entry)
{
    printf("fchown");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FCHMOD(RRLogEntry entry)
{
    printf("fchmod");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETREUID(RRLogEntry entry)
{
    printf("setreuid");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETREGID(RRLogEntry entry)
{
    printf("setregid");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RENAME(RRLogEntry entry)
{
    printf("rename");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FLOCK(RRLogEntry entry)
{
    printf("flock");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_MKFIFO(RRLogEntry entry)
{
    printf("mkfifo");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SENDTO(RRLogEntry entry)
{
    printf("sendto");
    printf("(%d, _, _, _, _, _", (int)entry.objectId);
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SHUTDOWN(RRLogEntry entry)
{
    printf("shutdown");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_MKDIR(RRLogEntry entry)
{
    printf("mkdir");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RMDIR(RRLogEntry entry)
{
    printf("rmdir");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_UTIMES(RRLogEntry entry)
{
    printf("utimes");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_ADJTIME(RRLogEntry entry)
{
    printf("adjtime");
    if ((int)entry.value[0] != -1) {
	printf("(_, olddelta");
    } else {
	printf("(_, olddelta");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_QUOTACTL(RRLogEntry entry)
{
    printf("quotactl");
    printf("(_, _, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LGETFH(RRLogEntry entry)
{
    printf("lgetfh");
    if ((int)entry.value[0] != -1) {
	printf("(_, fhp");
    } else {
	printf("(_, fhp");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETFH(RRLogEntry entry)
{
    printf("getfh");
    if ((int)entry.value[0] != -1) {
	printf("(_, fhp");
    } else {
	printf("(_, fhp");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETFIB(RRLogEntry entry)
{
    printf("setfib");
    printf("(%d", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_NTP_ADJTIME(RRLogEntry entry)
{
    printf("ntp_adjtime");
    if ((int)entry.value[0] != -1) {
	printf("(tp");
    } else {
	printf("(tp");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETGID(RRLogEntry entry)
{
    printf("setgid");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETEGID(RRLogEntry entry)
{
    printf("setegid");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETEUID(RRLogEntry entry)
{
    printf("seteuid");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_PATHCONF(RRLogEntry entry)
{
    printf("pathconf");
    printf("(_, _");
    printf(") = %ld", (long)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FPATHCONF(RRLogEntry entry)
{
    printf("fpathconf");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %ld", (long)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETRLIMIT(RRLogEntry entry)
{
    printf("getrlimit");
    if ((int)entry.value[0] != -1) {
	printf("(%d, rlp", (int)entry.objectId);
    } else {
	printf("(%d, rlp", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETRLIMIT(RRLogEntry entry)
{
    printf("setrlimit");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_UNDELETE(RRLogEntry entry)
{
    printf("undelete");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FUTIMES(RRLogEntry entry)
{
    printf("futimes");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_POLL(RRLogEntry entry)
{
    printf("poll");
    if ((int)entry.value[0] != -1) {
	printf("(fds, _, _");
    } else {
	printf("(fds, _, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SEMGET(RRLogEntry entry)
{
    printf("semget");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SEMOP(RRLogEntry entry)
{
    printf("semop");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SHMGET(RRLogEntry entry)
{
    printf("shmget");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CLOCK_SETTIME(RRLogEntry entry)
{
    printf("clock_settime");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CLOCK_GETRES(RRLogEntry entry)
{
    printf("clock_getres");
    if ((int)entry.value[0] != -1) {
	printf("(_, tp");
    } else {
	printf("(_, tp");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FFCLOCK_GETCOUNTER(RRLogEntry entry)
{
    printf("ffclock_getcounter");
    if ((int)entry.value[0] != -1) {
	printf("(ffcount");
    } else {
	printf("(ffcount");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FFCLOCK_SETESTIMATE(RRLogEntry entry)
{
    printf("ffclock_setestimate");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FFCLOCK_GETESTIMATE(RRLogEntry entry)
{
    printf("ffclock_getestimate");
    if ((int)entry.value[0] != -1) {
	printf("(cest");
    } else {
	printf("(cest");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_NTP_GETTIME(RRLogEntry entry)
{
    printf("ntp_gettime");
    if ((int)entry.value[0] != -1) {
	printf("(ntvp");
    } else {
	printf("(ntvp");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_ISSETUGID(RRLogEntry entry)
{
    printf("issetugid");
    printf("(");
    printf(") = %d", (int)entry.value[0]);

    printf("\n");
}

void
pretty_print_LCHOWN(RRLogEntry entry)
{
    printf("lchown");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LCHMOD(RRLogEntry entry)
{
    printf("lchmod");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LUTIMES(RRLogEntry entry)
{
    printf("lutimes");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_PREADV(RRLogEntry entry)
{
    printf("preadv");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FHOPEN(RRLogEntry entry)
{
    printf("fhopen");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETRESUID(RRLogEntry entry)
{
    printf("setresuid");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETRESGID(RRLogEntry entry)
{
    printf("setresgid");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTRCTL(RRLogEntry entry)
{
    printf("extattrctl");
    printf("(_, _, _, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_SET_FILE(RRLogEntry entry)
{
    printf("extattr_set_file");
    printf("(_, _, _, _, _");
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_GET_FILE(RRLogEntry entry)
{
    printf("extattr_get_file");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, _, data, _");
    } else {
	printf("(_, _, _, data, _");
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_DELETE_FILE(RRLogEntry entry)
{
    printf("extattr_delete_file");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETRESUID(RRLogEntry entry)
{
    printf("getresuid");
    if ((int)entry.value[0] != -1) {
	printf("(ruid, euid, suid");
    } else {
	printf("(ruid, euid, suid");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETRESGID(RRLogEntry entry)
{
    printf("getresgid");
    if ((int)entry.value[0] != -1) {
	printf("(rgid, egid, sgid");
    } else {
	printf("(rgid, egid, sgid");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_KQUEUE(RRLogEntry entry)
{
    printf("kqueue");
    printf("(");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_SET_FD(RRLogEntry entry)
{
    printf("extattr_set_fd");
    printf("(%d, _, _, _, _", (int)entry.objectId);
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_GET_FD(RRLogEntry entry)
{
    printf("extattr_get_fd");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, _, data, _", (int)entry.objectId);
    } else {
	printf("(%d, _, _, data, _", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_DELETE_FD(RRLogEntry entry)
{
    printf("extattr_delete_fd");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EACCESS(RRLogEntry entry)
{
    printf("eaccess");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_NMOUNT(RRLogEntry entry)
{
    printf("nmount");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_KENV(RRLogEntry entry)
{
    printf("kenv");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, value, _", (int)entry.objectId);
    } else {
	printf("(%d, _, value, _", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LCHFLAGS(RRLogEntry entry)
{
    printf("lchflags");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_UUIDGEN(RRLogEntry entry)
{
    printf("uuidgen");
    if ((int)entry.value[0] != -1) {
	printf("(store, _");
    } else {
	printf("(store, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SENDFILE(RRLogEntry entry)
{
    printf("sendfile");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, _, _, _, sbytes, _", (int)entry.objectId);
    } else {
	printf("(%d, _, _, _, _, sbytes, _", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_SET_LINK(RRLogEntry entry)
{
    printf("extattr_set_link");
    printf("(_, _, _, _, _");
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_GET_LINK(RRLogEntry entry)
{
    printf("extattr_get_link");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, _, data, _");
    } else {
	printf("(_, _, _, data, _");
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_DELETE_LINK(RRLogEntry entry)
{
    printf("extattr_delete_link");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_LIST_FD(RRLogEntry entry)
{
    printf("extattr_list_fd");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, data, _", (int)entry.objectId);
    } else {
	printf("(%d, _, data, _", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_LIST_FILE(RRLogEntry entry)
{
    printf("extattr_list_file");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, data, _");
    } else {
	printf("(_, _, data, _");
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_EXTATTR_LIST_LINK(RRLogEntry entry)
{
    printf("extattr_list_link");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, data, _");
    } else {
	printf("(_, _, data, _");
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_AUDIT(RRLogEntry entry)
{
    printf("audit");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_AUDITON(RRLogEntry entry)
{
    printf("auditon");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETAUID(RRLogEntry entry)
{
    printf("getauid");
    if ((int)entry.value[0] != -1) {
	printf("(auid");
    } else {
	printf("(auid");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETAUID(RRLogEntry entry)
{
    printf("setauid");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETAUDIT(RRLogEntry entry)
{
    printf("getaudit");
    if ((int)entry.value[0] != -1) {
	printf("(auditinfo");
    } else {
	printf("(auditinfo");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETAUDIT(RRLogEntry entry)
{
    printf("setaudit");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETAUDIT_ADDR(RRLogEntry entry)
{
    printf("getaudit_addr");
    if ((int)entry.value[0] != -1) {
	printf("(auditinfo_addr, _");
    } else {
	printf("(auditinfo_addr, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETAUDIT_ADDR(RRLogEntry entry)
{
    printf("setaudit_addr");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_AUDITCTL(RRLogEntry entry)
{
    printf("auditctl");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_PREAD(RRLogEntry entry)
{
    printf("pread");
    if ((int)entry.value[0] != -1) {
	printf("(%d, buf, _, _", (int)entry.objectId);
    } else {
	printf("(%d, buf, _, _", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_PWRITE(RRLogEntry entry)
{
    printf("pwrite");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LSEEK(RRLogEntry entry)
{
    printf("lseek");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %ld", (__off_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_TRUNCATE(RRLogEntry entry)
{
    printf("truncate");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FTRUNCATE(RRLogEntry entry)
{
    printf("ftruncate");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SHM_UNLINK(RRLogEntry entry)
{
    printf("shm_unlink");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CPUSET(RRLogEntry entry)
{
    printf("cpuset");
    if ((int)entry.value[0] != -1) {
	printf("(setid");
    } else {
	printf("(setid");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CPUSET_SETID(RRLogEntry entry)
{
    printf("cpuset_setid");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CPUSET_GETID(RRLogEntry entry)
{
    printf("cpuset_getid");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, _, setid");
    } else {
	printf("(_, _, _, setid");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CPUSET_GETAFFINITY(RRLogEntry entry)
{
    printf("cpuset_getaffinity");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, _, _, mask");
    } else {
	printf("(_, _, _, _, mask");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CPUSET_SETAFFINITY(RRLogEntry entry)
{
    printf("cpuset_setaffinity");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, _, _, mask");
    } else {
	printf("(_, _, _, _, mask");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FACCESSAT(RRLogEntry entry)
{
    printf("faccessat");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FCHMODAT(RRLogEntry entry)
{
    printf("fchmodat");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FCHOWNAT(RRLogEntry entry)
{
    printf("fchownat");
    printf("(%d, _, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LINKAT(RRLogEntry entry)
{
    printf("linkat");
    printf("(%d, _, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_MKDIRAT(RRLogEntry entry)
{
    printf("mkdirat");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_MKFIFOAT(RRLogEntry entry)
{
    printf("mkfifoat");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_OPENAT(RRLogEntry entry)
{
    printf("openat");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_READLINKAT(RRLogEntry entry)
{
    printf("readlinkat");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, buf, _", (int)entry.objectId);
    } else {
	printf("(%d, _, buf, _", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RENAMEAT(RRLogEntry entry)
{
    printf("renameat");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SYMLINKAT(RRLogEntry entry)
{
    printf("symlinkat");
    printf("(_, _, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_UNLINKAT(RRLogEntry entry)
{
    printf("unlinkat");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_LPATHCONF(RRLogEntry entry)
{
    printf("lpathconf");
    printf("(_, _");
    printf(") = %ld", (long)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CAP_ENTER(RRLogEntry entry)
{
    printf("cap_enter");
    printf("(");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CAP_GETMODE(RRLogEntry entry)
{
    printf("cap_getmode");
    if ((int)entry.value[0] != -1) {
	printf("(modep");
    } else {
	printf("(modep");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETLOGINCLASS(RRLogEntry entry)
{
    printf("getloginclass");
    if ((int)entry.value[0] != -1) {
	printf("(namebuf, _");
    } else {
	printf("(namebuf, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SETLOGINCLASS(RRLogEntry entry)
{
    printf("setloginclass");
    printf("(_");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RCTL_GET_RACCT(RRLogEntry entry)
{
    printf("rctl_get_racct");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, outbufp, _");
    } else {
	printf("(_, _, outbufp, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RCTL_GET_RULES(RRLogEntry entry)
{
    printf("rctl_get_rules");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, outbufp, _");
    } else {
	printf("(_, _, outbufp, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RCTL_GET_LIMITS(RRLogEntry entry)
{
    printf("rctl_get_limits");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, outbufp, _");
    } else {
	printf("(_, _, outbufp, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RCTL_ADD_RULE(RRLogEntry entry)
{
    printf("rctl_add_rule");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, outbufp, _");
    } else {
	printf("(_, _, outbufp, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_RCTL_REMOVE_RULE(RRLogEntry entry)
{
    printf("rctl_remove_rule");
    if ((int)entry.value[0] != -1) {
	printf("(_, _, outbufp, _");
    } else {
	printf("(_, _, outbufp, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_POSIX_FALLOCATE(RRLogEntry entry)
{
    printf("posix_fallocate");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_POSIX_FADVISE(RRLogEntry entry)
{
    printf("posix_fadvise");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CAP_RIGHTS_LIMIT(RRLogEntry entry)
{
    printf("cap_rights_limit");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CAP_IOCTLS_LIMIT(RRLogEntry entry)
{
    printf("cap_ioctls_limit");
    printf("(%d, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CAP_IOCTLS_GET(RRLogEntry entry)
{
    printf("cap_ioctls_get");
    if ((int)entry.value[0] != -1) {
	printf("(%d, cmds, _", (int)entry.objectId);
    } else {
	printf("(%d, cmds, _", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CAP_FCNTLS_LIMIT(RRLogEntry entry)
{
    printf("cap_fcntls_limit");
    printf("(%d, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CAP_FCNTLS_GET(RRLogEntry entry)
{
    printf("cap_fcntls_get");
    if ((int)entry.value[0] != -1) {
	printf("(%d, fcntlrightsp", (int)entry.objectId);
    } else {
	printf("(%d, fcntlrightsp", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_BINDAT(RRLogEntry entry)
{
    printf("bindat");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CONNECTAT(RRLogEntry entry)
{
    printf("connectat");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_CHFLAGSAT(RRLogEntry entry)
{
    printf("chflagsat");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_ACCEPT4(RRLogEntry entry)
{
    printf("accept4");
    if ((int)entry.value[0] != -1) {
	printf("(%d, name, anamelen, _", (int)entry.objectId);
    } else {
	printf("(%d, name, anamelen, _", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_PIPE2(RRLogEntry entry)
{
    printf("pipe2");
    if ((int)entry.value[0] != -1) {
	printf("(fildes, _");
    } else {
	printf("(fildes, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FDATASYNC(RRLogEntry entry)
{
    printf("fdatasync");
    printf("(%d", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FSTAT(RRLogEntry entry)
{
    printf("fstat");
    if ((int)entry.value[0] != -1) {
	struct stat	sb;
	char		str0[255];
	readData((uint8_t *) & sb, sizeof(sb));
	castor_xlat_stat(sb, str0);

	printf("(%d, %s", (int)entry.objectId, str0);
    } else {
	printf("(%d, sb", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FSTATAT(RRLogEntry entry)
{
    printf("fstatat");
    if ((int)entry.value[0] != -1) {
	struct stat	buf;
	char		str0[255];
	readData((uint8_t *) & buf, sizeof(buf));
	castor_xlat_stat(buf, str0);

	printf("(%d, _, %s, _", (int)entry.objectId, str0);
    } else {
	printf("(%d, _, buf, _", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FHSTAT(RRLogEntry entry)
{
    printf("fhstat");
    if ((int)entry.value[0] != -1) {
	struct stat	sb;
	char		str0[255];
	readData((uint8_t *) & sb, sizeof(sb));
	castor_xlat_stat(sb, str0);

	printf("(_, %s", str0);
    } else {
	printf("(_, sb");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETDIRENTRIES(RRLogEntry entry)
{
    printf("getdirentries");
    if ((int)entry.value[0] != -1) {
	printf("(%d, buf, _, basep", (int)entry.objectId);
    } else {
	printf("(%d, buf, _, basep", (int)entry.objectId);
    }
    printf(") = %zd", (ssize_t) entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_STATFS(RRLogEntry entry)
{
    printf("statfs");
    if ((int)entry.value[0] != -1) {
	struct stat	buf;
	char		str0[255];
	readData((uint8_t *) & buf, sizeof(buf));
	castor_xlat_stat(buf, str0);

	printf("(_, %s", str0);
    } else {
	printf("(_, buf");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FSTATFS(RRLogEntry entry)
{
    printf("fstatfs");
    if ((int)entry.value[0] != -1) {
	struct stat	buf;
	char		str0[255];
	readData((uint8_t *) & buf, sizeof(buf));
	castor_xlat_stat(buf, str0);

	printf("(%d, %s", (int)entry.objectId, str0);
    } else {
	printf("(%d, buf", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_GETFSSTAT(RRLogEntry entry)
{
    printf("getfsstat");
    if ((int)entry.value[0] != -1) {
	printf("(buf, _, _");
    } else {
	printf("(buf, _, _");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_FHSTATFS(RRLogEntry entry)
{
    printf("fhstatfs");
    if ((int)entry.value[0] != -1) {
	struct stat	buf;
	char		str0[255];
	readData((uint8_t *) & buf, sizeof(buf));
	castor_xlat_stat(buf, str0);

	printf("(_, %s", str0);
    } else {
	printf("(_, buf");
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_MKNODAT(RRLogEntry entry)
{
    printf("mknodat");
    printf("(%d, _, _, _", (int)entry.objectId);
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_KEVENT(RRLogEntry entry)
{
    printf("kevent");
    if ((int)entry.value[0] != -1) {
	printf("(%d, _, _, eventlist, _, _", (int)entry.objectId);
    } else {
	printf("(%d, _, _, eventlist, _, _", (int)entry.objectId);
    }
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_SWAPOFF(RRLogEntry entry)
{
    printf("swapoff");
    printf("(_, _");
    printf(") = %d", (int)entry.value[0]);

    if ((int)entry.value[0] == -1) {
	printf(" [errno: %s]", castor_xlat_errno((int)entry.value[1]));
    }

    printf("\n");
}

void
pretty_print_NULL_EVENT(RRLogEntry entry)
{
    printf("[builtin] null_event()\n");
}

void
pretty_print_EXIT(RRLogEntry entry)
{
    printf("[builtin] exit()\n");
}

void
pretty_print_DATA(RRLogEntry entry)
{
    printf("[builtin] <data>\n");
}

void
pretty_print_LOCKED_EVENT(RRLogEntry entry)
{
    printf("[builtin] locked_event()\n");
}

void
pretty_print_MUTEX_INIT(RRLogEntry entry)
{
    printf("[builtin] mutex_init()\n");
}

void
pretty_print_MUTEX_DESTROY(RRLogEntry entry)
{
    printf("[builtin] mutex_destroy()\n");
}

void
pretty_print_MUTEX_LOCK(RRLogEntry entry)
{
    printf("[builtin] mutex_lock()\n");
}

void
pretty_print_MUTEX_TRYLOCK(RRLogEntry entry)
{
    printf("[builtin] mutex_trylock()\n");
}

void
pretty_print_MUTEX_UNLOCK(RRLogEntry entry)
{
    printf("[builtin] mutex_unlock()\n");
}

void
pretty_print_THREAD_CREATE(RRLogEntry entry)
{
    printf("[builtin] thread_create()\n");
}

void
pretty_print_FORKEND(RRLogEntry entry)
{
    printf("[builtin] forkend()\n");
}

void
pretty_print_COND_INIT(RRLogEntry entry)
{
    printf("[builtin] cond_init()\n");
}

void
pretty_print_COND_DESTROY(RRLogEntry entry)
{
    printf("[builtin] cond_destroy()\n");
}

void
pretty_print_COND_WAIT(RRLogEntry entry)
{
    printf("[builtin] cond_wait()\n");
}

void
pretty_print_COND_SIGNAL(RRLogEntry entry)
{
    printf("[builtin] cond_signal()\n");
}

void
pretty_print_COND_BROADCAST(RRLogEntry entry)
{
    printf("[builtin] cond_broadcast()\n");
}

void
pretty_print_THREAD_ONCE(RRLogEntry entry)
{
    printf("[builtin] thread_once()\n");
}

void
pretty_print_BARRIER_INIT(RRLogEntry entry)
{
    printf("[builtin] barrier_init()\n");
}

void
pretty_print_BARRIER_DESTROY(RRLogEntry entry)
{
    printf("[builtin] barrier_destroy()\n");
}

void
pretty_print_BARRIER_WAIT(RRLogEntry entry)
{
    printf("[builtin] barrier_wait()\n");
}

void
pretty_print_SPIN_INIT(RRLogEntry entry)
{
    printf("[builtin] spin_init()\n");
}

void
pretty_print_SPIN_DESTROY(RRLogEntry entry)
{
    printf("[builtin] spin_destroy()\n");
}

void
pretty_print_SPIN_TRYLOCK(RRLogEntry entry)
{
    printf("[builtin] spin_trylock()\n");
}

void
pretty_print_SPIN_LOCK(RRLogEntry entry)
{
    printf("[builtin] spin_lock()\n");
}

void
pretty_print_SPIN_UNLOCK(RRLogEntry entry)
{
    printf("[builtin] spin_unlock()\n");
}

void
pretty_print_RWLOCK_INIT(RRLogEntry entry)
{
    printf("[builtin] rwlock_init()\n");
}

void
pretty_print_RWLOCK_DESTROY(RRLogEntry entry)
{
    printf("[builtin] rwlock_destroy()\n");
}

void
pretty_print_RWLOCK_UNLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_unlock()\n");
}

void
pretty_print_RWLOCK_RDLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_rdlock()\n");
}

void
pretty_print_RWLOCK_TRYRDLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_tryrdlock()\n");
}

void
pretty_print_RWLOCK_WRLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_wrlock()\n");
}

void
pretty_print_RWLOCK_TRYWRLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_trywrlock()\n");
}

void
pretty_print_RWLOCK_TIMEDRDLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_timedrdlock()\n");
}

void
pretty_print_RWLOCK_TIMEDWRLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_timedwrlock()\n");
}

void
pretty_print_MUTEX_TIMEDLOCK(RRLogEntry entry)
{
    printf("[builtin] mutex_timedlock()\n");
}

void
pretty_print_THREAD_EXIT(RRLogEntry entry)
{
    printf("[builtin] thread_exit()\n");
}

void
pretty_print_THREAD_DETACH(RRLogEntry entry)
{
    printf("[builtin] thread_detach()\n");
}

void
pretty_print_THREAD_JOIN(RRLogEntry entry)
{
    printf("[builtin] thread_join()\n");
}

void
pretty_print_THREAD_KILL(RRLogEntry entry)
{
    printf("[builtin] thread_kill()\n");
}

void
pretty_print_THREAD_TIMEDJOIN(RRLogEntry entry)
{
    printf("[builtin] thread_timedjoin()\n");
}

void
pretty_print_RDTSC(RRLogEntry entry)
{
    printf("[builtin] rdtsc()\n");
}

void
pretty_print_ATOMIC_LOAD(RRLogEntry entry)
{
    printf("[builtin] atomic_load()\n");
}

void
pretty_print_ATOMIC_STORE(RRLogEntry entry)
{
    printf("[builtin] atomic_store()\n");
}

void
pretty_print_ATOMIC_RMW(RRLogEntry entry)
{
    printf("[builtin] atomic_rmw()\n");
}

void
pretty_print_ATOMIC_XCHG(RRLogEntry entry)
{
    printf("[builtin] atomic_xchg()\n");
}

void
pretty_print_INLINE_ASM(RRLogEntry entry)
{
    printf("[builtin] inline_asm()\n");
}

void
pretty_print_WAIT(RRLogEntry entry)
{
    printf("[builtin] wait()\n");
}

void
pretty_print_SEMCTL(RRLogEntry entry)
{
    printf("[builtin] semctl()\n");
}

void
pretty_print_SEM_OPEN(RRLogEntry entry)
{
    printf("[builtin] sem_open()\n");
}

void
pretty_print_SEM_CLOSE(RRLogEntry entry)
{
    printf("[builtin] sem_close()\n");
}

void
pretty_print_SEM_UNLINK(RRLogEntry entry)
{
    printf("[builtin] sem_unlink()\n");
}

void
pretty_print_SEM_POST_START(RRLogEntry entry)
{
    printf("[builtin] sem_post_start()\n");
}

void
pretty_print_SEM_POST_END(RRLogEntry entry)
{
    printf("[builtin] sem_post_end()\n");
}

void
pretty_print_SEM_WAIT(RRLogEntry entry)
{
    printf("[builtin] sem_wait()\n");
}

void
pretty_print_SEM_TRYWAIT(RRLogEntry entry)
{
    printf("[builtin] sem_trywait()\n");
}

void
pretty_print_SEM_TIMEDWAIT(RRLogEntry entry)
{
    printf("[builtin] sem_timedwait()\n");
}

void
pretty_print_SEM_GETVALUE(RRLogEntry entry)
{
    printf("[builtin] sem_getvalue()\n");
}

void
pretty_print_SEM_INIT(RRLogEntry entry)
{
    printf("[builtin] sem_init()\n");
}

void
pretty_print_SEM_DESTROY(RRLogEntry entry)
{
    printf("[builtin] sem_destroy()\n");
}

void
pretty_print_MMAPFD(RRLogEntry entry)
{
    printf("[builtin] mmapfd()\n");
}

void
pretty_print_PIPE(RRLogEntry entry)
{
    printf("[builtin] pipe()\n");
}

void
pretty_print_GETTIME(RRLogEntry entry)
{
    printf("[builtin] gettime()\n");
}

void
pretty_print_SYSCTL(RRLogEntry entry)
{
    printf("[builtin] sysctl()\n");
}

void
pretty_print_GETCWD(RRLogEntry entry)
{
    printf("[builtin] getcwd()\n");
}
