
/*** !!! this code has been autogenerated by utils/gen_sal.py, do not modify it directly. !!! ***/


#include <stdio.h>
#include <errno.h>
#include <time.h>
#include <signal.h>


#include <unistd.h>
#include <fcntl.h>
#include <dirent.h>
#include <kenv.h>
#include <poll.h>

#include <semaphore.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/ptrace.h>
#include <sys/event.h>
#include <sys/socket.h>
#include <sys/uio.h>
#include <sys/resource.h>
#include <sys/param.h>
#include <sys/cpuset.h>
#include <sys/mount.h>
#include <sys/syscall.h>
#include <sys/stat.h>
#include <sys/capsicum.h>
#include <sys/extattr.h>
#include <sys/time.h>
#include <sys/uuid.h>
#include <sys/reboot.h>
#include <ufs/ufs/quota.h>
#include <sys/timex.h>
#include <sys/timeffc.h>
#include <sys/rctl.h>
#include <bsm/audit.h>
#include <sys/ucred.h>

#ifndef GEN_SAL

#include <castor/debug.h>
#include <castor/rrlog.h>
#include <castor/rrplay.h>
#include <castor/rrgq.h>
#include <castor/mtx.h>
#include <castor/events.h>

#endif
#include "castor_xlat.h"
void
pretty_print_FORK(RRLogEntry entry)
{
    printf("fork() = %d", (pid_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_READ(RRLogEntry entry)
{
    printf("read(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_WRITE(RRLogEntry entry)
{
    printf("write(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_OPEN(RRLogEntry entry)
{
    printf("open() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CLOSE(RRLogEntry entry)
{
    printf("close(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LINK(RRLogEntry entry)
{
    printf("link() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_UNLINK(RRLogEntry entry)
{
    printf("unlink() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CHDIR(RRLogEntry entry)
{
    printf("chdir() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FCHDIR(RRLogEntry entry)
{
    printf("fchdir(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CHMOD(RRLogEntry entry)
{
    printf("chmod() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CHOWN(RRLogEntry entry)
{
    printf("chown() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETPID(RRLogEntry entry)
{
    printf("getpid() = %d", (pid_t) entry.value[0]);
    printf("\n");
}

void
pretty_print_MOUNT(RRLogEntry entry)
{
    printf("mount() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_UNMOUNT(RRLogEntry entry)
{
    printf("unmount() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETUID(RRLogEntry entry)
{
    printf("setuid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETUID(RRLogEntry entry)
{
    printf("getuid() = %d", (uid_t) entry.value[0]);
    printf("\n");
}

void
pretty_print_GETEUID(RRLogEntry entry)
{
    printf("geteuid() = %d", (uid_t) entry.value[0]);
    printf("\n");
}

void
pretty_print_RECVMSG(RRLogEntry entry)
{
    printf("recvmsg(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SENDMSG(RRLogEntry entry)
{
    printf("sendmsg(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RECVFROM(RRLogEntry entry)
{
    printf("recvfrom(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_ACCEPT(RRLogEntry entry)
{
    printf("accept(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETPEERNAME(RRLogEntry entry)
{
    printf("getpeername(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETSOCKNAME(RRLogEntry entry)
{
    printf("getsockname(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_ACCESS(RRLogEntry entry)
{
    printf("access() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CHFLAGS(RRLogEntry entry)
{
    printf("chflags() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FCHFLAGS(RRLogEntry entry)
{
    printf("fchflags(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETPPID(RRLogEntry entry)
{
    printf("getppid() = %d", (pid_t) entry.value[0]);
    printf("\n");
}

void
pretty_print_DUP(RRLogEntry entry)
{
    printf("dup(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETEGID(RRLogEntry entry)
{
    printf("getegid() = %d", (gid_t) entry.value[0]);
    printf("\n");
}

void
pretty_print_GETGID(RRLogEntry entry)
{
    printf("getgid() = %d", (gid_t) entry.value[0]);
    printf("\n");
}

void
pretty_print_ACCT(RRLogEntry entry)
{
    printf("acct() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_IOCTL(RRLogEntry entry)
{
    printf("ioctl(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_REBOOT(RRLogEntry entry)
{
    printf("reboot(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SYMLINK(RRLogEntry entry)
{
    printf("symlink() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_READLINK(RRLogEntry entry)
{
    printf("readlink() = %zd", (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_UMASK(RRLogEntry entry)
{
    printf("umask() = %d", (mode_t) entry.value[0]);
    printf("\n");
}

void
pretty_print_CHROOT(RRLogEntry entry)
{
    printf("chroot() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETGROUPS(RRLogEntry entry)
{
    printf("getgroups(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETGROUPS(RRLogEntry entry)
{
    printf("setgroups(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETITIMER(RRLogEntry entry)
{
    printf("setitimer(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SWAPON(RRLogEntry entry)
{
    printf("swapon() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETITIMER(RRLogEntry entry)
{
    printf("getitimer(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETDTABLESIZE(RRLogEntry entry)
{
    printf("getdtablesize() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_DUP2(RRLogEntry entry)
{
    printf("dup2(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FCNTL(RRLogEntry entry)
{
    printf("fcntl(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SELECT(RRLogEntry entry)
{
    printf("select(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FSYNC(RRLogEntry entry)
{
    printf("fsync(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETPRIORITY(RRLogEntry entry)
{
    printf("setpriority(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SOCKET(RRLogEntry entry)
{
    printf("socket(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CONNECT(RRLogEntry entry)
{
    printf("connect(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETPRIORITY(RRLogEntry entry)
{
    printf("getpriority(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_BIND(RRLogEntry entry)
{
    printf("bind(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETSOCKOPT(RRLogEntry entry)
{
    printf("setsockopt(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LISTEN(RRLogEntry entry)
{
    printf("listen(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETTIMEOFDAY(RRLogEntry entry)
{
    printf("gettimeofday() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETRUSAGE(RRLogEntry entry)
{
    printf("getrusage(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETSOCKOPT(RRLogEntry entry)
{
    printf("getsockopt(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_READV(RRLogEntry entry)
{
    printf("readv(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_WRITEV(RRLogEntry entry)
{
    printf("writev(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETTIMEOFDAY(RRLogEntry entry)
{
    printf("settimeofday() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FCHOWN(RRLogEntry entry)
{
    printf("fchown(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FCHMOD(RRLogEntry entry)
{
    printf("fchmod(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETREUID(RRLogEntry entry)
{
    printf("setreuid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETREGID(RRLogEntry entry)
{
    printf("setregid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RENAME(RRLogEntry entry)
{
    printf("rename() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FLOCK(RRLogEntry entry)
{
    printf("flock(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_MKFIFO(RRLogEntry entry)
{
    printf("mkfifo() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SENDTO(RRLogEntry entry)
{
    printf("sendto(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SHUTDOWN(RRLogEntry entry)
{
    printf("shutdown(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_MKDIR(RRLogEntry entry)
{
    printf("mkdir() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RMDIR(RRLogEntry entry)
{
    printf("rmdir() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_UTIMES(RRLogEntry entry)
{
    printf("utimes() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_ADJTIME(RRLogEntry entry)
{
    printf("adjtime() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_QUOTACTL(RRLogEntry entry)
{
    printf("quotactl() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LGETFH(RRLogEntry entry)
{
    printf("lgetfh() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETFH(RRLogEntry entry)
{
    printf("getfh() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETFIB(RRLogEntry entry)
{
    printf("setfib(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_NTP_ADJTIME(RRLogEntry entry)
{
    printf("ntp_adjtime() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETGID(RRLogEntry entry)
{
    printf("setgid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETEGID(RRLogEntry entry)
{
    printf("setegid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETEUID(RRLogEntry entry)
{
    printf("seteuid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_PATHCONF(RRLogEntry entry)
{
    printf("pathconf() = %ld", (long)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FPATHCONF(RRLogEntry entry)
{
    printf("fpathconf(%d,...) = %ld", (int)entry.objectId, (long)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETRLIMIT(RRLogEntry entry)
{
    printf("getrlimit(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETRLIMIT(RRLogEntry entry)
{
    printf("setrlimit(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_UNDELETE(RRLogEntry entry)
{
    printf("undelete() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FUTIMES(RRLogEntry entry)
{
    printf("futimes(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_POLL(RRLogEntry entry)
{
    printf("poll() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SEMGET(RRLogEntry entry)
{
    printf("semget() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SEMOP(RRLogEntry entry)
{
    printf("semop(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SHMGET(RRLogEntry entry)
{
    printf("shmget() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CLOCK_SETTIME(RRLogEntry entry)
{
    printf("clock_settime() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CLOCK_GETRES(RRLogEntry entry)
{
    printf("clock_getres() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FFCLOCK_GETCOUNTER(RRLogEntry entry)
{
    printf("ffclock_getcounter() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FFCLOCK_SETESTIMATE(RRLogEntry entry)
{
    printf("ffclock_setestimate() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FFCLOCK_GETESTIMATE(RRLogEntry entry)
{
    printf("ffclock_getestimate() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_NTP_GETTIME(RRLogEntry entry)
{
    printf("ntp_gettime() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_ISSETUGID(RRLogEntry entry)
{
    printf("issetugid() = %d", (int)entry.value[0]);
    printf("\n");
}

void
pretty_print_LCHOWN(RRLogEntry entry)
{
    printf("lchown() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LCHMOD(RRLogEntry entry)
{
    printf("lchmod() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LUTIMES(RRLogEntry entry)
{
    printf("lutimes() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_PREADV(RRLogEntry entry)
{
    printf("preadv(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FHOPEN(RRLogEntry entry)
{
    printf("fhopen() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETRESUID(RRLogEntry entry)
{
    printf("setresuid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETRESGID(RRLogEntry entry)
{
    printf("setresgid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTRCTL(RRLogEntry entry)
{
    printf("extattrctl() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_SET_FILE(RRLogEntry entry)
{
    printf("extattr_set_file() = %zd", (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_GET_FILE(RRLogEntry entry)
{
    printf("extattr_get_file() = %zd", (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_DELETE_FILE(RRLogEntry entry)
{
    printf("extattr_delete_file() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETRESUID(RRLogEntry entry)
{
    printf("getresuid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETRESGID(RRLogEntry entry)
{
    printf("getresgid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_KQUEUE(RRLogEntry entry)
{
    printf("kqueue() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_SET_FD(RRLogEntry entry)
{
    printf("extattr_set_fd(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_GET_FD(RRLogEntry entry)
{
    printf("extattr_get_fd(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_DELETE_FD(RRLogEntry entry)
{
    printf("extattr_delete_fd(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EACCESS(RRLogEntry entry)
{
    printf("eaccess() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_NMOUNT(RRLogEntry entry)
{
    printf("nmount() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_KENV(RRLogEntry entry)
{
    printf("kenv(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LCHFLAGS(RRLogEntry entry)
{
    printf("lchflags() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_UUIDGEN(RRLogEntry entry)
{
    printf("uuidgen() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SENDFILE(RRLogEntry entry)
{
    printf("sendfile(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_SET_LINK(RRLogEntry entry)
{
    printf("extattr_set_link() = %zd", (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_GET_LINK(RRLogEntry entry)
{
    printf("extattr_get_link() = %zd", (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_DELETE_LINK(RRLogEntry entry)
{
    printf("extattr_delete_link() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SWAPOFF(RRLogEntry entry)
{
    printf("swapoff() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_LIST_FD(RRLogEntry entry)
{
    printf("extattr_list_fd(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_LIST_FILE(RRLogEntry entry)
{
    printf("extattr_list_file() = %zd", (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_EXTATTR_LIST_LINK(RRLogEntry entry)
{
    printf("extattr_list_link() = %zd", (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_AUDIT(RRLogEntry entry)
{
    printf("audit() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_AUDITON(RRLogEntry entry)
{
    printf("auditon(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETAUID(RRLogEntry entry)
{
    printf("getauid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETAUID(RRLogEntry entry)
{
    printf("setauid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETAUDIT(RRLogEntry entry)
{
    printf("getaudit() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETAUDIT(RRLogEntry entry)
{
    printf("setaudit() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETAUDIT_ADDR(RRLogEntry entry)
{
    printf("getaudit_addr() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETAUDIT_ADDR(RRLogEntry entry)
{
    printf("setaudit_addr() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_AUDITCTL(RRLogEntry entry)
{
    printf("auditctl() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_PREAD(RRLogEntry entry)
{
    printf("pread(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_PWRITE(RRLogEntry entry)
{
    printf("pwrite(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LSEEK(RRLogEntry entry)
{
    printf("lseek(%d,...) = %ld", (int)entry.objectId, (__off_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_TRUNCATE(RRLogEntry entry)
{
    printf("truncate() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FTRUNCATE(RRLogEntry entry)
{
    printf("ftruncate(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SHM_OPEN(RRLogEntry entry)
{
    printf("shm_open() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SHM_UNLINK(RRLogEntry entry)
{
    printf("shm_unlink() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CPUSET(RRLogEntry entry)
{
    printf("cpuset() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CPUSET_SETID(RRLogEntry entry)
{
    printf("cpuset_setid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CPUSET_GETID(RRLogEntry entry)
{
    printf("cpuset_getid() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CPUSET_GETAFFINITY(RRLogEntry entry)
{
    printf("cpuset_getaffinity() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CPUSET_SETAFFINITY(RRLogEntry entry)
{
    printf("cpuset_setaffinity() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FACCESSAT(RRLogEntry entry)
{
    printf("faccessat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FCHMODAT(RRLogEntry entry)
{
    printf("fchmodat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FCHOWNAT(RRLogEntry entry)
{
    printf("fchownat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LINKAT(RRLogEntry entry)
{
    printf("linkat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_MKDIRAT(RRLogEntry entry)
{
    printf("mkdirat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_MKFIFOAT(RRLogEntry entry)
{
    printf("mkfifoat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_OPENAT(RRLogEntry entry)
{
    printf("openat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_READLINKAT(RRLogEntry entry)
{
    printf("readlinkat(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RENAMEAT(RRLogEntry entry)
{
    printf("renameat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SYMLINKAT(RRLogEntry entry)
{
    printf("symlinkat() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_UNLINKAT(RRLogEntry entry)
{
    printf("unlinkat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_LPATHCONF(RRLogEntry entry)
{
    printf("lpathconf() = %ld", (long)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CAP_ENTER(RRLogEntry entry)
{
    printf("cap_enter() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CAP_GETMODE(RRLogEntry entry)
{
    printf("cap_getmode() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETLOGINCLASS(RRLogEntry entry)
{
    printf("getloginclass() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_SETLOGINCLASS(RRLogEntry entry)
{
    printf("setloginclass() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RCTL_GET_RACCT(RRLogEntry entry)
{
    printf("rctl_get_racct() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RCTL_GET_RULES(RRLogEntry entry)
{
    printf("rctl_get_rules() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RCTL_GET_LIMITS(RRLogEntry entry)
{
    printf("rctl_get_limits() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RCTL_ADD_RULE(RRLogEntry entry)
{
    printf("rctl_add_rule() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_RCTL_REMOVE_RULE(RRLogEntry entry)
{
    printf("rctl_remove_rule() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_POSIX_FALLOCATE(RRLogEntry entry)
{
    printf("posix_fallocate(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_POSIX_FADVISE(RRLogEntry entry)
{
    printf("posix_fadvise(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CAP_RIGHTS_LIMIT(RRLogEntry entry)
{
    printf("cap_rights_limit(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CAP_IOCTLS_LIMIT(RRLogEntry entry)
{
    printf("cap_ioctls_limit(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CAP_IOCTLS_GET(RRLogEntry entry)
{
    printf("cap_ioctls_get(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CAP_FCNTLS_LIMIT(RRLogEntry entry)
{
    printf("cap_fcntls_limit(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CAP_FCNTLS_GET(RRLogEntry entry)
{
    printf("cap_fcntls_get(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_BINDAT(RRLogEntry entry)
{
    printf("bindat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CONNECTAT(RRLogEntry entry)
{
    printf("connectat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_CHFLAGSAT(RRLogEntry entry)
{
    printf("chflagsat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_ACCEPT4(RRLogEntry entry)
{
    printf("accept4(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_PIPE2(RRLogEntry entry)
{
    printf("pipe2() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FDATASYNC(RRLogEntry entry)
{
    printf("fdatasync(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FSTAT(RRLogEntry entry)
{
    printf("fstat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FSTATAT(RRLogEntry entry)
{
    printf("fstatat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FHSTAT(RRLogEntry entry)
{
    printf("fhstat() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETDIRENTRIES(RRLogEntry entry)
{
    printf("getdirentries(%d,...) = %zd", (int)entry.objectId, (ssize_t) entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_STATFS(RRLogEntry entry)
{
    printf("statfs() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FSTATFS(RRLogEntry entry)
{
    printf("fstatfs(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_GETFSSTAT(RRLogEntry entry)
{
    printf("getfsstat() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_FHSTATFS(RRLogEntry entry)
{
    printf("fhstatfs() = %d", (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_MKNODAT(RRLogEntry entry)
{
    printf("mknodat(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_KEVENT(RRLogEntry entry)
{
    printf("kevent(%d,...) = %d", (int)entry.objectId, (int)entry.value[0]);
    if ((int)entry.value[0] == -1) {
	printf("[errno:%s]", castor_xlat_errno((int)entry.value[1]));
    }
    printf("\n");
}

void
pretty_print_NULL_EVENT(RRLogEntry entry)
{
    printf("[builtin] null_event()\n");
}

void
pretty_print_EXIT(RRLogEntry entry)
{
    printf("[builtin] exit()\n");
}

void
pretty_print_DATA(RRLogEntry entry)
{
    printf("[builtin] <data>\n");
}

void
pretty_print_LOCKED_EVENT(RRLogEntry entry)
{
    printf("[builtin] locked_event()\n");
}

void
pretty_print_MUTEX_INIT(RRLogEntry entry)
{
    printf("[builtin] mutex_init()\n");
}

void
pretty_print_MUTEX_DESTROY(RRLogEntry entry)
{
    printf("[builtin] mutex_destroy()\n");
}

void
pretty_print_MUTEX_LOCK(RRLogEntry entry)
{
    printf("[builtin] mutex_lock()\n");
}

void
pretty_print_MUTEX_TRYLOCK(RRLogEntry entry)
{
    printf("[builtin] mutex_trylock()\n");
}

void
pretty_print_MUTEX_UNLOCK(RRLogEntry entry)
{
    printf("[builtin] mutex_unlock()\n");
}

void
pretty_print_THREAD_CREATE(RRLogEntry entry)
{
    printf("[builtin] thread_create()\n");
}

void
pretty_print_FORKEND(RRLogEntry entry)
{
    printf("[builtin] forkend()\n");
}

void
pretty_print_COND_INIT(RRLogEntry entry)
{
    printf("[builtin] cond_init()\n");
}

void
pretty_print_COND_DESTROY(RRLogEntry entry)
{
    printf("[builtin] cond_destroy()\n");
}

void
pretty_print_COND_WAIT(RRLogEntry entry)
{
    printf("[builtin] cond_wait()\n");
}

void
pretty_print_COND_SIGNAL(RRLogEntry entry)
{
    printf("[builtin] cond_signal()\n");
}

void
pretty_print_COND_BROADCAST(RRLogEntry entry)
{
    printf("[builtin] cond_broadcast()\n");
}

void
pretty_print_THREAD_ONCE(RRLogEntry entry)
{
    printf("[builtin] thread_once()\n");
}

void
pretty_print_BARRIER_INIT(RRLogEntry entry)
{
    printf("[builtin] barrier_init()\n");
}

void
pretty_print_BARRIER_DESTROY(RRLogEntry entry)
{
    printf("[builtin] barrier_destroy()\n");
}

void
pretty_print_BARRIER_WAIT(RRLogEntry entry)
{
    printf("[builtin] barrier_wait()\n");
}

void
pretty_print_SPIN_INIT(RRLogEntry entry)
{
    printf("[builtin] spin_init()\n");
}

void
pretty_print_SPIN_DESTROY(RRLogEntry entry)
{
    printf("[builtin] spin_destroy()\n");
}

void
pretty_print_SPIN_TRYLOCK(RRLogEntry entry)
{
    printf("[builtin] spin_trylock()\n");
}

void
pretty_print_SPIN_LOCK(RRLogEntry entry)
{
    printf("[builtin] spin_lock()\n");
}

void
pretty_print_SPIN_UNLOCK(RRLogEntry entry)
{
    printf("[builtin] spin_unlock()\n");
}

void
pretty_print_RWLOCK_INIT(RRLogEntry entry)
{
    printf("[builtin] rwlock_init()\n");
}

void
pretty_print_RWLOCK_DESTROY(RRLogEntry entry)
{
    printf("[builtin] rwlock_destroy()\n");
}

void
pretty_print_RWLOCK_UNLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_unlock()\n");
}

void
pretty_print_RWLOCK_RDLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_rdlock()\n");
}

void
pretty_print_RWLOCK_TRYRDLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_tryrdlock()\n");
}

void
pretty_print_RWLOCK_WRLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_wrlock()\n");
}

void
pretty_print_RWLOCK_TRYWRLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_trywrlock()\n");
}

void
pretty_print_RWLOCK_TIMEDRDLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_timedrdlock()\n");
}

void
pretty_print_RWLOCK_TIMEDWRLOCK(RRLogEntry entry)
{
    printf("[builtin] rwlock_timedwrlock()\n");
}

void
pretty_print_MUTEX_TIMEDLOCK(RRLogEntry entry)
{
    printf("[builtin] mutex_timedlock()\n");
}

void
pretty_print_THREAD_EXIT(RRLogEntry entry)
{
    printf("[builtin] thread_exit()\n");
}

void
pretty_print_THREAD_DETACH(RRLogEntry entry)
{
    printf("[builtin] thread_detach()\n");
}

void
pretty_print_THREAD_JOIN(RRLogEntry entry)
{
    printf("[builtin] thread_join()\n");
}

void
pretty_print_THREAD_KILL(RRLogEntry entry)
{
    printf("[builtin] thread_kill()\n");
}

void
pretty_print_THREAD_TIMEDJOIN(RRLogEntry entry)
{
    printf("[builtin] thread_timedjoin()\n");
}

void
pretty_print_RDTSC(RRLogEntry entry)
{
    printf("[builtin] rdtsc()\n");
}

void
pretty_print_ATOMIC_LOAD(RRLogEntry entry)
{
    printf("[builtin] atomic_load()\n");
}

void
pretty_print_ATOMIC_STORE(RRLogEntry entry)
{
    printf("[builtin] atomic_store()\n");
}

void
pretty_print_ATOMIC_RMW(RRLogEntry entry)
{
    printf("[builtin] atomic_rmw()\n");
}

void
pretty_print_ATOMIC_XCHG(RRLogEntry entry)
{
    printf("[builtin] atomic_xchg()\n");
}

void
pretty_print_INLINE_ASM(RRLogEntry entry)
{
    printf("[builtin] inline_asm()\n");
}

void
pretty_print_WAIT(RRLogEntry entry)
{
    printf("[builtin] wait()\n");
}

void
pretty_print_SEMCTL(RRLogEntry entry)
{
    printf("[builtin] semctl()\n");
}

void
pretty_print_SEM_OPEN(RRLogEntry entry)
{
    printf("[builtin] sem_open()\n");
}

void
pretty_print_SEM_CLOSE(RRLogEntry entry)
{
    printf("[builtin] sem_close()\n");
}

void
pretty_print_SEM_UNLINK(RRLogEntry entry)
{
    printf("[builtin] sem_unlink()\n");
}

void
pretty_print_SEM_POST_START(RRLogEntry entry)
{
    printf("[builtin] sem_post_start()\n");
}

void
pretty_print_SEM_POST_END(RRLogEntry entry)
{
    printf("[builtin] sem_post_end()\n");
}

void
pretty_print_SEM_WAIT(RRLogEntry entry)
{
    printf("[builtin] sem_wait()\n");
}

void
pretty_print_SEM_TRYWAIT(RRLogEntry entry)
{
    printf("[builtin] sem_trywait()\n");
}

void
pretty_print_SEM_TIMEDWAIT(RRLogEntry entry)
{
    printf("[builtin] sem_timedwait()\n");
}

void
pretty_print_SEM_GETVALUE(RRLogEntry entry)
{
    printf("[builtin] sem_getvalue()\n");
}

void
pretty_print_SEM_INIT(RRLogEntry entry)
{
    printf("[builtin] sem_init()\n");
}

void
pretty_print_SEM_DESTROY(RRLogEntry entry)
{
    printf("[builtin] sem_destroy()\n");
}

void
pretty_print_MMAPFD(RRLogEntry entry)
{
    printf("[builtin] mmapfd()\n");
}

void
pretty_print_PIPE(RRLogEntry entry)
{
    printf("[builtin] pipe()\n");
}

void
pretty_print_GETTIME(RRLogEntry entry)
{
    printf("[builtin] gettime()\n");
}

void
pretty_print_SYSCTL(RRLogEntry entry)
{
    printf("[builtin] sysctl()\n");
}

void
pretty_print_GETCWD(RRLogEntry entry)
{
    printf("[builtin] getcwd()\n");
}
