
Import('env')

env.Program("record", ["record.c"],
            LINKFLAGS = ["-static"],
            LIBPATH = ["#build/lib/Common"],
            LIBS = ["elf", "execinfo", "edit", "pthread", "CastorCommon"])
