
import os

Import('env')
Import('cp')

testbench_deps = [ ]

for t in Glob('#build/unit-tests/*.c'):
    env.Depends(t, cp)
    d = env.Program(t,
                    CPPFLAGS = ["-fpass-plugin=$CASTORPASS"],
                    LINKFLAGS = ["-static"],
                    LIBPATH = ["${BUILDROOT}/../build/lib/Runtime",
                               "${BUILDROOT}/../build/lib/ThreadRuntime"],
                    LIBS = ["CastorRuntime", "c", "CastorThreadRuntime", "thr"])
    testbench_deps.append(d)

AlwaysBuild(Alias('testbench', testbench_deps, "unit-tests/testbench.py"))

