
import os

Import('env')
Import('cp')

testbench_deps = [ ]

for t in Glob('#build/unit-tests/*.c'):
    env.Depends(t, cp)
    d = env.Program(t,
                    CPPFLAGS = ["-fpass-plugin=$CASTORPASS"],
                    LIBS = ["c", "thr", "elf", "execinfo"])
    testbench_deps.append(d)

AlwaysBuild(Alias('testbench', testbench_deps, "unit-tests/testbench.py"))

