
Import('env')

common_src = [
    "cli.c",
    "ft.c",
    "proc.c",
    "runtime.c",
]

env.StaticLibrary("libcommon.a", common_src)

record_src = ["record.c"]
replay_src = ["replay.c"]
baseline_src = ["baseline.c"]

env.Program("record", record_src,
        LIBPATH = ["#build/record"], LIBS = ["common", "edit", "pthread"])
env.Program("replay", replay_src,
        LIBPATH = ["#build/record"], LIBS = ["common", "edit", "pthread"])
env.Program("baseline", baseline_src,
        LIBPATH = ["#build/record"], LIBS = ["common", "edit", "pthread"])

