
/*** this code has been autogenerated by code in utils/gen, do not modify it directly. ***/


#include <unistd.h>
#include <sys/types.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/syscall.h>
#include <sys/stat.h>

#include <castor/debug.h>
#include <castor/rrlog.h>
#include <castor/rrplay.h>
#include <castor/rrgq.h>
#include <castor/mtx.h>
#include <castor/events.h>

#include "util.h"




#include <sys/param.h>
#include <sys/sysent.h>
#include <sys/sysproto.h>
#include <sys/mount.h>
#include <sys/socket.h>
#include <sys/user.h>

#if !defined(PAD64_REQUIRED) && (defined(__powerpc__) || defined(__mips__))
#define PAD64_REQUIRED
#endif













int
__rr_stat(const char * path, struct stat * ub)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_stat, path, ub);
	case RRMODE_RECORD:
	    result = syscall(SYS_stat, path, ub);
	    RRRecordI(RREVENT_STAT, result);
		if (result == 0) {
			logData((uint8_t *)ub, sizeof(struct stat));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayI(RREVENT_STAT, &result);
		if (result == 0) {
			logData((uint8_t *)ub, sizeof(struct stat));
		}
	    break;
    }
    return result;
}

int
__rr_lstat(const char * path, struct stat * ub)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_lstat, path, ub);
	case RRMODE_RECORD:
	    result = syscall(SYS_lstat, path, ub);
	    RRRecordI(RREVENT_LSTAT, result);
		if (result == 0) {
			logData((uint8_t *)ub, sizeof(struct stat));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayI(RREVENT_LSTAT, &result);
		if (result == 0) {
			logData((uint8_t *)ub, sizeof(struct stat));
		}
	    break;
    }
    return result;
}

ssize_t
__rr_readlink(const char * path, char * buf, size_t count)
{
	ssize_t result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_readlink, path, buf, count);
	case RRMODE_RECORD:
	    result = syscall(SYS_readlink, path, buf, count);
	    RRRecordS(RREVENT_READLINK, result);
		if (result != -1) {
			logData((uint8_t *)buf, count * sizeof(char));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayS(RREVENT_READLINK, &result);
		if (result != -1) {
			logData((uint8_t *)buf, count * sizeof(char));
		}
	    break;
    }
    return result;
}

int
__rr_getrusage(int who, struct rusage * rusage)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_getrusage, who, rusage);
	case RRMODE_RECORD:
	    result = syscall(SYS_getrusage, who, rusage);
	    RRRecordOI(RREVENT_GETRUSAGE, who, result);
		if (result == 0) {
			logData((uint8_t *)rusage, sizeof(struct rusage));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayOI(RREVENT_GETRUSAGE, who, &result);
		if (result == 0) {
			logData((uint8_t *)rusage, sizeof(struct rusage));
		}
	    break;
    }
    return result;
}

int
__rr_shutdown(int s, int how)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_shutdown, s, how);
	case RRMODE_RECORD:
	    result = syscall(SYS_shutdown, s, how);
	    RRRecordOI(RREVENT_SHUTDOWN, s, result);
	    break;
	case RRMODE_REPLAY:
	    RRReplayOI(RREVENT_SHUTDOWN, s, &result);
	    break;
    }
    return result;
}

int
__rr_getrlimit(int which, struct rlimit * rlp)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_getrlimit, which, rlp);
	case RRMODE_RECORD:
	    result = syscall(SYS_getrlimit, which, rlp);
	    RRRecordOI(RREVENT_GETRLIMIT, which, result);
		if (result == 0) {
			logData((uint8_t *)rlp, sizeof(struct rlimit));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayOI(RREVENT_GETRLIMIT, which, &result);
		if (result == 0) {
			logData((uint8_t *)rlp, sizeof(struct rlimit));
		}
	    break;
    }
    return result;
}

int
__rr_setrlimit(int which, const struct rlimit * rlp)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_setrlimit, which, rlp);
	case RRMODE_RECORD:
	    result = syscall(SYS_setrlimit, which, rlp);
	    RRRecordOI(RREVENT_SETRLIMIT, which, result);
	    break;
	case RRMODE_REPLAY:
	    RRReplayOI(RREVENT_SETRLIMIT, which, &result);
	    break;
    }
    return result;
}

int
__rr_cpuset(cpusetid_t * setid)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_cpuset, setid);
	case RRMODE_RECORD:
	    result = syscall(SYS_cpuset, setid);
	    RRRecordI(RREVENT_CPUSET, result);
		if (result == 0) {
			logData((uint8_t *)setid, sizeof(cpusetid_t));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayI(RREVENT_CPUSET, &result);
		if (result == 0) {
			logData((uint8_t *)setid, sizeof(cpusetid_t));
		}
	    break;
    }
    return result;
}

int
__rr_cpuset_setid(cpuwhich_t which, id_t id, cpusetid_t setid)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_cpuset_setid, which, id, setid);
	case RRMODE_RECORD:
	    result = syscall(SYS_cpuset_setid, which, id, setid);
	    RRRecordI(RREVENT_CPUSET_SETID, result);
	    break;
	case RRMODE_REPLAY:
	    RRReplayI(RREVENT_CPUSET_SETID, &result);
	    break;
    }
    return result;
}

int
__rr_cpuset_getid(cpulevel_t level, cpuwhich_t which, id_t id, cpusetid_t * setid)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_cpuset_getid, level, which, id, setid);
	case RRMODE_RECORD:
	    result = syscall(SYS_cpuset_getid, level, which, id, setid);
	    RRRecordI(RREVENT_CPUSET_GETID, result);
		if (result == 0) {
			logData((uint8_t *)setid, sizeof(cpusetid_t));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayI(RREVENT_CPUSET_GETID, &result);
		if (result == 0) {
			logData((uint8_t *)setid, sizeof(cpusetid_t));
		}
	    break;
    }
    return result;
}

int
__rr_cpuset_getaffinity(cpulevel_t level, cpuwhich_t which, id_t id, size_t cpusetsize, cpuset_t * mask)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_cpuset_getaffinity, level, which, id, cpusetsize, mask);
	case RRMODE_RECORD:
	    result = syscall(SYS_cpuset_getaffinity, level, which, id, cpusetsize, mask);
	    RRRecordI(RREVENT_CPUSET_GETAFFINITY, result);
		if (result == 0) {
			logData((uint8_t *)mask, sizeof(cpuset_t));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayI(RREVENT_CPUSET_GETAFFINITY, &result);
		if (result == 0) {
			logData((uint8_t *)mask, sizeof(cpuset_t));
		}
	    break;
    }
    return result;
}

int
__rr_cpuset_setaffinity(cpulevel_t level, cpuwhich_t which, id_t id, size_t cpusetsize, const cpuset_t * mask)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_cpuset_setaffinity, level, which, id, cpusetsize, mask);
	case RRMODE_RECORD:
	    result = syscall(SYS_cpuset_setaffinity, level, which, id, cpusetsize, mask);
	    RRRecordI(RREVENT_CPUSET_SETAFFINITY, result);
		if (result == 0) {
			logData((uint8_t *)mask, sizeof(const cpuset_t));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayI(RREVENT_CPUSET_SETAFFINITY, &result);
		if (result == 0) {
			logData((uint8_t *)mask, sizeof(const cpuset_t));
		}
	    break;
    }
    return result;
}

ssize_t
__rr_readlinkat(int fd, const char * path, char * buf, size_t bufsize)
{
	ssize_t result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_readlinkat, fd, path, buf, bufsize);
	case RRMODE_RECORD:
	    result = syscall(SYS_readlinkat, fd, path, buf, bufsize);
	    RRRecordOS(RREVENT_READLINKAT, fd, result);
		if (result != -1) {
			logData((uint8_t *)buf, bufsize);
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayOS(RREVENT_READLINKAT, fd, &result);
		if (result != -1) {
			logData((uint8_t *)buf, bufsize);
		}
	    break;
    }
    return result;
}

int
__rr_fstat(int fd, struct stat * sb)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_fstat, fd, sb);
	case RRMODE_RECORD:
	    result = syscall(SYS_fstat, fd, sb);
	    RRRecordOI(RREVENT_FSTAT, fd, result);
		if (result == 0) {
			logData((uint8_t *)sb, sizeof(struct stat));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayOI(RREVENT_FSTAT, fd, &result);
		if (result == 0) {
			logData((uint8_t *)sb, sizeof(struct stat));
		}
	    break;
    }
    return result;
}

int
__rr_fstatat(int fd, const char * path, struct stat * buf, int flag)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_fstatat, fd, path, buf, flag);
	case RRMODE_RECORD:
	    result = syscall(SYS_fstatat, fd, path, buf, flag);
	    RRRecordOI(RREVENT_FSTATAT, fd, result);
		if (result == 0) {
			logData((uint8_t *)buf, sizeof(struct stat));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayOI(RREVENT_FSTATAT, fd, &result);
		if (result == 0) {
			logData((uint8_t *)buf, sizeof(struct stat));
		}
	    break;
    }
    return result;
}

int
__rr_statfs(const char * path, struct statfs * buf)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_statfs, path, buf);
	case RRMODE_RECORD:
	    result = syscall(SYS_statfs, path, buf);
	    RRRecordI(RREVENT_STATFS, result);
		if (result == 0) {
			logData((uint8_t *)buf, sizeof(struct statfs));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayI(RREVENT_STATFS, &result);
		if (result == 0) {
			logData((uint8_t *)buf, sizeof(struct statfs));
		}
	    break;
    }
    return result;
}

int
__rr_fstatfs(int fd, struct statfs * buf)
{
	int result;

    switch (rrMode) {
	case RRMODE_NORMAL:
	    return syscall(SYS_fstatfs, fd, buf);
	case RRMODE_RECORD:
	    result = syscall(SYS_fstatfs, fd, buf);
	    RRRecordOI(RREVENT_FSTATFS, fd, result);
		if (result == 0) {
			logData((uint8_t *)buf, sizeof(struct statfs));
		}
	    break;
	case RRMODE_REPLAY:
	    RRReplayOI(RREVENT_FSTATFS, fd, &result);
		if (result == 0) {
			logData((uint8_t *)buf, sizeof(struct statfs));
		}
	    break;
    }
    return result;
}

BIND_REF(stat);
BIND_REF(lstat);
BIND_REF(readlink);
BIND_REF(getrusage);
BIND_REF(shutdown);
BIND_REF(getrlimit);
BIND_REF(setrlimit);
BIND_REF(cpuset);
BIND_REF(cpuset_setid);
BIND_REF(cpuset_getid);
BIND_REF(cpuset_getaffinity);
BIND_REF(cpuset_setaffinity);
BIND_REF(readlinkat);
BIND_REF(fstat);
BIND_REF(fstatat);
BIND_REF(statfs);
BIND_REF(fstatfs);
