
Import('env')

src = [
    "runtime.c",
    "debug.c",
    "util.c",
    "freebsd.c",
    "events.c",
    "events_freebsd.c",
    "events_id.c",
    "events_mem.c",
    "events_thread.c",
    "events_llvm.c",
    "rr_assert.c",
    "rr_fdprintf.c",
    # Backtrace Support
    "/usr/lib/libexecinfo.a",
    "/usr/lib/libelf.a"
]

# Made global to make compilation_db work
env["CPPPATH"].append("#sysroot-src/lib/libc/include")

env.ObjectLibrary("libCastorRuntime.o", src)

