
Import('env')

src = [
    "runtime.c",
    "debug.c",
    "util.c",
    "fdinfo.c",
    "freebsd.c",
    "events.c",
    "events_freebsd.c",
    "events_mem.c",
    "events_posix.c",
    "events_proc.c",
    "events_sysv.c",
    "events_time.c",
    "events_llvm.c",
    "rr_assert.c",
    "rr_fdprintf.c",
]

env_libsys = env.Clone()

# Made global to make compilation_db work
env_libsys["CPPPATH"].append("#sysroot-src/lib/libc/include")

env_libsys["LINKFLAGS"].append("-nodefaultlibs")

env_libsys.SharedLibrary("libsys_castor.so", src, LIBS = ["compiler_rt"])

#rt = env.CopyFile("$SYSROOT/usr/lib/libCastorRuntime.a", 
#"#build/lib/Runtime/libCastorRuntime.a")
#env.Alias("CastorRuntime", rt)

