
Import('env')

env.Program("baseline", ["baseline.c"],
            CPPPATH = ["#build/lib/Common"],
            LIBPATH = ["#build/lib/Common"],
            LIBS = ["CastorCommon", "edit", "pthread"])

