
/*** this code has been autogenerated by code in utils/gen, do not modify it directly. ***/


#ifndef __EVENTS_GEN_H
#define __EVENTS_GEN_H


#define RREVENT_TABLE_GEN\
	RREVENT(CPUSET,	0xA000)\
	RREVENT(CPUSET_SETID,	0xA001)\
	RREVENT(CPUSET_GETID,	0xA002)\
	RREVENT(CPUSET_GETAFFINITY,	0xA003)\
	RREVENT(CPUSET_SETAFFINITY,	0xA004)
#endif
